apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a83mal5nx-nodejs
  janus-idp.io/tekton: a83mal5nx-nodejs
  backstage.io/kubernetes-id: a83mal5nx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a83mal5nx-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
